use wdk_sys::*;

pub mod unicode_string;

pub type Void = core::ffi::c_void;
pub type UChar = u8;
pub type Uint2B = u16;
pub type Uint4B = u32;
pub type Uint8B = u64;
pub type Char = i8;
pub type Int4B = i32;
pub type Int8B = i64;

#[repr(C, align(8))]
pub struct PEB {
    InheritedAddressSpace: UChar,
    ReadImageFileExecOptions: UChar,
    BeingDebugged: UChar,
    BitField: UChar,
    /*ImageUsesLargePages : Pos 0, 1 Bit,
    IsProtectedProcess : Pos 1, 1 Bit,
    IsImageDynamicallyRelocated : Pos 2, 1 Bit,
    SkipPatchingUser32Forwarders : Pos 3, 1 Bit,
    IsPackagedProcess : Pos 4, 1 Bit,
    IsAppContainer   : Pos 5, 1 Bit,
    IsProtectedProcessLight : Pos 6, 1 Bit,
         IsLongPathAwareProcess : Pos 7, 1 Bit*/
    Mutant: *mut Void,
    ImageBaseAddress: *mut Void,
    Ldr: *mut Void, //_PEB_LDR_DATA,
    ProcessParameters: *mut RTL_USER_PROCESS_PARAMETERS,
    SubSystemData: *mut Void,
    ProcessHeap: *mut Void,
    FastPebLock: *mut Void, // _RTL_CRITICAL_SECTION,
    AtlThunkSListPtr: *mut _SLIST_HEADER,
    IFEOKey: *mut Void,
    CrossProcessFlags: Uint4B,
    /*ProcessInJob     : Pos 0, 1 Bit
    ProcessInitializing : Pos 1, 1 Bit
    ProcessUsingVEH  : Pos 2, 1 Bit
    ProcessUsingVCH  : Pos 3, 1 Bit
    ProcessUsingFTH  : Pos 4, 1 Bit
    ProcessPreviouslyThrottled : Pos 5, 1 Bit
    ProcessCurrentlyThrottled : Pos 6, 1 Bit
    ProcessImagesHotPatched : Pos 7, 1 Bit
    ReservedBits0    : Pos 8, 24 Bits*/
    KernelCallbackTable: *mut Void,
    UserSharedInfoPtr: *mut Void,
    SystemReserved: Uint4B,
    AtlThunkSListPtr32: Uint4B,
    ApiSetMap: *mut Void,
    TlsExpansionCounter: Uint4B,
    TlsBitmap: *mut Void,
    TlsBitmapBits: [Uint4B; 2],
    ReadOnlySharedMemoryBase: *mut Void,
    SharedData: *mut Void,
    ReadOnlyStaticServerData: *mut *mut Void,
    AnsiCodePageData: *mut Void,
    OemCodePageData: *mut Void,
    UnicodeCaseTableData: *mut Void,
    NumberOfProcessors: Uint4B,
    NtGlobalFlag: Uint4B,
    CriticalSectionTimeout: _LARGE_INTEGER,
    HeapSegmentReserve: Uint8B,
    HeapSegmentCommit: Uint8B,
    HeapDeCommitTotalFreeThreshold: Uint8B,
    HeapDeCommitFreeBlockThreshold: Uint8B,
    NumberOfHeaps: Uint4B,
    MaximumNumberOfHeaps: Uint4B,
    ProcessHeaps: *mut *mut Void,
    GdiSharedHandleTable: *mut Void,
    ProcessStarterHelper: *mut Void,
    GdiDCAttributeList: Uint4B,
    LoaderLock: *mut Void,
    OSMajorVersion: Uint4B,
    OSMinorVersion: Uint4B,
    OSBuildNumber: Uint2B,
    OSCSDVersion: Uint2B,
    OSPlatformId: Uint4B,
    ImageSubsystem: Uint4B,
    ImageSubsystemMajorVersion: Uint4B,
    ImageSubsystemMinorVersion: Uint4B,
    ActiveProcessAffinityMask: Uint8B,
    GdiHandleBuffer: [Uint4B; 60],
    PostProcessInitRoutine: *mut Void,
    TlsExpansionBitmap: *mut Void, // _RTL_BITMAP,
    TlsExpansionBitmapBits: [Uint4B; 32],
    SessionId: Uint4B,
    AppCompatFlags: _ULARGE_INTEGER,
    AppCompatFlagsUser: _ULARGE_INTEGER,
    pShimData: *mut Void,
    AppCompatInfo: *mut Void,
    CSDVersion: _UNICODE_STRING,
    ActivationContextData: *mut Void,     //_ACTIVATION_CONTEXT_DATA,
    ProcessAssemblyStorageMap: *mut Void, //_ASSEMBLY_STORAGE_MAP,
    SystemDefaultActivationContextData: *mut Void, // _ACTIVATION_CONTEXT_DATA,
    SystemAssemblyStorageMap: *mut Void,  //_ASSEMBLY_STORAGE_MAP
    MinimumStackCommit: Uint8B,
    SparePointers: [*mut Void; 2],
    PatchLoaderData: *mut Void,
    ChpeV2ProcessInfo: *mut Void,
    AppModelFeatureState: Uint4B,
    SpareUlongs: [Uint4B; 2],
    ActiveCodePage: Uint2B,
    OemCodePage: Uint2B,
    UseCaseMapping: Uint2B,
    UnusedNlsField: Uint2B,
    WerRegistrationData: *mut Void,
    WerShipAssertPtr: *mut Void,
    EcCodeBitMap: *mut Void,
    pImageHeaderHash: *mut Void,
    TracingFlags: Uint4B,
    CsrServerReadOnlySharedMemoryBase: Uint8B,
    TppWorkerpListLock: Uint8B,
    TppWorkerpList: _LIST_ENTRY,
    WaitOnAddressHashTable: [*mut Void; 128],
    TelemetryCoverageHeader: *mut Void,
    CloudFileFlags: Uint4B,
    CloudFileDiagFlags: Uint4B,
    PlaceholderCompatibilityMode: Char,
    LeapSecondData: *mut Void,
    LeapSecondFlags: Uint4B,
    NtGlobalFlag2: Uint4B,
    ExtendedFeatureDisableMask: Uint8B,
    Win32ClientProcInfo: *mut Void,
}

#[repr(C)]
struct RTL_USER_PROCESS_PARAMETERS {
    pub maximum_length: u32,
    pub length: u32,
    pub flags: u32,
    pub debug_flags: u32,
    pub console_handle: PVOID,
    pub console_flags: u32,
    pub standard_input: PVOID,
    pub standard_output: PVOID,
    pub standard_error: PVOID,
    pub current_directory: CURDIR,
    pub dll_path: UNICODE_STRING,
    pub image_path_name: UNICODE_STRING,
    pub command_line: UNICODE_STRING,
    pub environment: PVOID,
    pub starting_x: u32,
    pub starting_y: u32,
    pub count_x: u32,
    pub count_y: u32,
    pub count_chars_x: u32,
    pub count_chars_y: u32,
    pub fill_attribute: u32,
    pub window_flags: u32,
    pub show_window_flags: u32,
    pub window_title: UNICODE_STRING,
    pub desktop_info: UNICODE_STRING,
    pub shell_info: UNICODE_STRING,
    pub runtime_data: UNICODE_STRING,
    pub current_directores: [RTL_DRIVE_LETTER_CURDIR; 32],
    pub environment_size: u64,
    pub environment_version: u64,
    pub package_dependency_data: PVOID,
    pub process_group_id: u32,
    pub loader_threads: u32,
    pub redirection_dll_name: UNICODE_STRING,
    pub heap_partition_name: UNICODE_STRING,
    pub default_threadpool_cpu_set_masks: *mut u64,
    pub default_threadpool_cpu_set_mask_count: u32,
    pub default_threadpool_thread_maximum: u32,
    pub heap_memory_type_mask: u32,
    pub attribute_list: PVOID,
}

#[repr(C)]
struct RTL_DRIVE_LETTER_CURDIR {
    pub flags: u16,
    pub length: u16,
    pub time_stamp: u32,
    pub dos_path: UNICODE_STRING,
}

#[repr(C)]
struct CURDIR {
    pub dos_path: UNICODE_STRING,
    pub handle: HANDLE,
}

pub type _KAB_UM_PROCESS_CONTEXT = [Void; 2];
pub type _KEXECUTE_OPTIONS = [UChar; 5];
pub type _KGROUP_MASK = [Void; 2];
pub type _KI_IDEAL_PROCESSOR_ASSIGNMENT_BLOCK = Void;
pub type _KSTACK_COUNT = Void;
pub type _KSCHEDULING_GROUP = Void;
pub type _KPROCESS_AVAILABLE_CPU_STATE = Void;
pub type _KPROCESS = KPROCESS;

#[repr(C, align(8))]
pub struct KPROCESS {
    pub Header: _DISPATCHER_HEADER,
    pub ProfileListHead: _LIST_ENTRY,
    pub DirectoryTableBase: Uint8B,
    pub ThreadListHead: _LIST_ENTRY,
    pub ProcessLock: Uint4B,
    pub ProcessTimerDelay: Uint4B,
    pub DeepFreezeStartTime: Uint8B,
    pub Affinity: *mut _KAFFINITY_EX,
    pub AutoBoostState: _KAB_UM_PROCESS_CONTEXT,
    pub ReadyListHead: _LIST_ENTRY,
    pub SwapListEntry: _SINGLE_LIST_ENTRY,
    pub ActiveProcessors: *mut _KAFFINITY_EX,
    /*AutoAlignment    : Pos 0, 1 Bit,
    pub DisableBoost     : Pos 1, 1 Bit,
    pub DisableQuantum   : Pos 2, 1 Bit,
    pub DeepFreeze       : Pos 3, 1 Bit,
    pub TimerVirtualization : Pos 4, 1 Bit,
    pub CheckStackExtents : Pos 5, 1 Bit,
    pub CacheIsolationEnabled : Pos 6, 1 Bit,
    pub PpmPolicy        : Pos 7, 4 Bits,
    pub VaSpaceDeleted   : Pos 11, 1 Bit,
    pub MultiGroup       : Pos 12, 1 Bit,
    pub ForegroundProcess : Pos 13, 1 Bit,
    pub ReservedFlags    : Pos 14, 18 Bits*/
    pub ProcessFlags: Int4B,
    pub Spare0c: Uint4B,
    pub BasePriority: Char,
    pub QuantumReset: Char,
    pub Visited: Char,
    pub Flags: _KEXECUTE_OPTIONS,
    pub ActiveGroupsMask: _KGROUP_MASK,
    pub ActiveGroupPadding: [Uint8B; 2],
    pub IdealProcessorAssignmentBlock: *mut _KI_IDEAL_PROCESSOR_ASSIGNMENT_BLOCK,
    pub Padding: [Uint8B; 6],
    pub Padding2: Uint4B,
    pub SchedulerAssistYieldBoostCount: Uint4B,
    pub SchedulerAssistYieldBoostAllowedTime: Int8B,
    pub Spare0d: Uint4B,
    pub IdealGlobalNode: Uint2B,
    pub Spare1: Uint2B,
    pub StackCount: _KSTACK_COUNT,
    pub ProcessListEntry: _LIST_ENTRY,
    pub CycleTime: Uint8B,
    pub ContextSwitches: Uint8B,
    pub SchedulingGroup: *mut _KSCHEDULING_GROUP,
    pub KernelTime: Uint8B,
    pub UserTime: Uint8B,
    pub ReadyTime: Uint8B,
    pub FreezeCount: Uint4B,
    pub Spare4: Uint4B,
    pub UserDirectoryTableBase: Uint8B,
    pub AddressPolicy: UChar,
    pub InstrumentationCallback: *mut Void,
    pub SecureState: Void,
    pub KernelWaitTime: Uint8B,
    pub UserWaitTime: Uint8B,
    pub LastRebalanceQpc: Uint8B,
    pub PerProcessorCycleTimes: *mut Void,
    pub ExtendedFeatureDisableMask: Uint8B,
    pub PrimaryGroup: Uint2B,
    pub UserCetLogging: *mut Void,
    pub CpuPartitionList: _LIST_ENTRY,
    pub AvailableCpuState: *mut _KPROCESS_AVAILABLE_CPU_STATE,
}

pub type _EX_PUSH_LOCK = Void;
pub type _EX_FAST_REF = Void;
pub type _ETHREAD = Void;
pub type _RTL_AVL_TREE = Void;
pub type _PAGEFAULT_HISTORY = Void;
pub type _PSP_SESSION_SPACE = Void;
pub type _EPROCESS_QUOTA_BLOCK = Void;
pub type _HANDLE_TABLE = Void;
pub type _EWOW64PROCESS = Void;
pub type _SE_AUDIT_PROCESS_CREATION_INFO = Void;
pub type _MMSUPPORT_FULL = [u8; 0x140];
pub type _ALPC_PROCESS_CONTEXT = [u8; 0x20];
pub type _PO_DIAG_STACK_RECORD = Void;
pub type _INVERTED_FUNCTION_TABLE_KERNEL_MODE = Void;
pub type _PS_PROTECTION = u8;
pub type _PROCESS_DISK_COUNTERS = Void;
pub type _PO_PROCESS_ENERGY_CONTEXT = Void;
pub type _PS_INTERLOCKED_TIMER_DELAY_VALUES = Void;
pub type _PS_PROCESS_WAKE_INFORMATION = [u8; 0x30];
pub type _PS_DYNAMIC_ENFORCED_ADDRESS_RANGES = [Void; 2];
pub type _PS_SYSCALL_PROVIDER = Void;
pub type _PSP_SYSCALL_PROVIDER_DISPATCH_CONTEXT = Void;
pub type _PROCESS_EXECUTION = Void;

#[repr(C, align(8))]
pub struct _EPROCESS {
    Pcb: _KPROCESS,
    ProcessLock: _EX_PUSH_LOCK,
    UniqueProcessId: *mut Void,
    ActiveProcessLinks: _LIST_ENTRY,
    RundownProtect: _EX_RUNDOWN_REF,
    Flags2: Uint4B,
    /*JobNotReallyActive : Pos 0, 1 Bit,
    AccountingFolded : Pos 1, 1 Bit,
    NewProcessReported : Pos 2, 1 Bit,
    ExitProcessReported : Pos 3, 1 Bit,
    ReportCommitChanges : Pos 4, 1 Bit,
    LastReportMemory : Pos 5, 1 Bit,
    ForceWakeCharge  : Pos 6, 1 Bit,
    CrossSessionCreate : Pos 7, 1 Bit,
    NeedsHandleRundown : Pos 8, 1 Bit,
    RefTraceEnabled  : Pos 9, 1 Bit,
    PicoCreated      : Pos 10, 1 Bit,
    EmptyJobEvaluated : Pos 11, 1 Bit,
    DefaultPagePriority : Pos 12, 3 Bits,
    PrimaryTokenFrozen : Pos 15, 1 Bit,
    ProcessVerifierTarget : Pos 16, 1 Bit,
    RestrictSetThreadContext : Pos 17, 1 Bit,
    AffinityPermanent : Pos 18, 1 Bit,
    AffinityUpdateEnable : Pos 19, 1 Bit,
    PropagateNode    : Pos 20, 1 Bit,
    ExplicitAffinity : Pos 21, 1 Bit,
    Flags2Available1 : Pos 22, 2 Bits,
    EnableReadVmLogging : Pos 24, 1 Bit,
    EnableWriteVmLogging : Pos 25, 1 Bit,
    FatalAccessTerminationRequested : Pos 26, 1 Bit,
    DisableSystemAllowedCpuSet : Pos 27, 1 Bit,
    Flags2Available2 : Pos 28, 3 Bits,
    InPrivate        : Pos 31, 1 Bit*/
    Flags: Uint4B,
    /*CreateReported   : Pos 0, 1 Bit,
    NoDebugInherit   : Pos 1, 1 Bit,
    ProcessExiting   : Pos 2, 1 Bit,
    ProcessDelete    : Pos 3, 1 Bit,
    ManageExecutableMemoryWrites : Pos 4, 1 Bit,
    VmDeleted        : Pos 5, 1 Bit,
    OutswapEnabled   : Pos 6, 1 Bit,
    Outswapped       : Pos 7, 1 Bit,
    FailFastOnCommitFail : Pos 8, 1 Bit,
    Wow64VaSpace4Gb  : Pos 9, 1 Bit,
    AddressSpaceInitialized : Pos 10, 2 Bits,
    SetTimerResolution : Pos 12, 1 Bit,
    BreakOnTermination : Pos 13, 1 Bit,
    DeprioritizeViews : Pos 14, 1 Bit,
    WriteWatch       : Pos 15, 1 Bit,
    ProcessInSession : Pos 16, 1 Bit,
    OverrideAddressSpace : Pos 17, 1 Bit,
    HasAddressSpace  : Pos 18, 1 Bit,
    LaunchPrefetched : Pos 19, 1 Bit,
    Reserved         : Pos 20, 1 Bit,
    VmTopDown        : Pos 21, 1 Bit,
    ImageNotifyDone  : Pos 22, 1 Bit,
    PdeUpdateNeeded  : Pos 23, 1 Bit,
    VdmAllowed       : Pos 24, 1 Bit,
    ProcessRundown   : Pos 25, 1 Bit,
    ProcessInserted  : Pos 26, 1 Bit,
    DefaultIoPriority : Pos 27, 3 Bits,
    ProcessSelfDelete : Pos 30, 1 Bit,
    SetTimerResolutionLink : Pos 31, 1 Bit*/
    CreateTime: _LARGE_INTEGER,
    ProcessQuotaUsage: [Uint8B; 2],
    ProcessQuotaPeak: [Uint8B; 2],
    PeakVirtualSize: Uint8B,
    VirtualSize: Uint8B,
    SessionProcessLinks: _LIST_ENTRY,
    ExceptionPortData: *mut Void,
    ExceptionPortValue: Uint8B,
    //ExceptionPortState : Pos 0, 3 Bits,
    Token: _EX_FAST_REF,
    MmReserved: Uint8B,
    AddressCreationLock: _EX_PUSH_LOCK,
    PageTableCommitmentLock: _EX_PUSH_LOCK,
    RotateInProgress: *mut _ETHREAD,
    ForkInProgress: *mut _ETHREAD,
    CommitChargeJob: *mut _EJOB,
    CloneRoot: _RTL_AVL_TREE,
    NumberOfPrivatePages: Uint8B,
    MmReserved2: Uint8B,
    Win32Process: *mut Void,
    Job: *mut _EJOB,
    SectionObject: *mut Void,
    SectionBaseAddress: *mut Void,
    Cookie: Uint4B,
    WorkingSetWatch: *mut _PAGEFAULT_HISTORY,
    Win32WindowStation: *mut Void,
    InheritedFromUniqueProcessId: *mut Void,
    OwnerProcessId: Uint8B,
    Peb: *mut _PEB,
    Session: *mut _PSP_SESSION_SPACE,
    Spare1: *mut Void,
    QuotaBlock: *mut _EPROCESS_QUOTA_BLOCK,
    ObjectTable: *mut _HANDLE_TABLE,
    DebugPort: *mut Void,
    WoW64Process: *mut _EWOW64PROCESS,
    DeviceMap: _EX_FAST_REF,
    EtwDataSource: *mut Void,
    PageDirectoryPte: Uint8B,
    ImageFilePointer: *mut _FILE_OBJECT,
    ImageFileName: [UChar; 15],
    PriorityClass: UChar,
    SecurityPort: *mut Void,
    SeAuditProcessCreationInfo: _SE_AUDIT_PROCESS_CREATION_INFO,
    JobLinks: _LIST_ENTRY,
    HighestUserAddress: *mut Void,
    ThreadListHead: _LIST_ENTRY,
    ActiveThreads: Uint4B,
    ImagePathHash: Uint4B,
    DefaultHardErrorProcessing: Uint4B,
    LastThreadExitStatus: Int4B,
    PrefetchTrace: _EX_FAST_REF,
    LockedPagesList: *mut Void,
    ReadOperationCount: _LARGE_INTEGER,
    WriteOperationCount: _LARGE_INTEGER,
    OtherOperationCount: _LARGE_INTEGER,
    ReadTransferCount: _LARGE_INTEGER,
    WriteTransferCount: _LARGE_INTEGER,
    OtherTransferCount: _LARGE_INTEGER,
    CommitChargeLimit: Uint8B,
    CommitCharge: Uint8B,
    CommitChargePeak: Uint8B,
    Vm: _MMSUPPORT_FULL,
    MmProcessLinks: _LIST_ENTRY,
    ModifiedPageCount: Uint4B,
    ExitStatus: Int4B,
    VadRoot: _RTL_AVL_TREE,
    VadHint: *mut Void,
    VadCount: Uint8B,
    VadPhysicalPages: Uint8B,
    VadPhysicalPagesLimit: Uint8B,
    AlpcContext: _ALPC_PROCESS_CONTEXT,
    TimerResolutionLink: _LIST_ENTRY,
    TimerResolutionStackRecord: *mut _PO_DIAG_STACK_RECORD,
    RequestedTimerResolution: Uint4B,
    SmallestTimerResolution: Uint4B,
    ExitTime: _LARGE_INTEGER,
    InvertedFunctionTable: *mut _INVERTED_FUNCTION_TABLE_KERNEL_MODE,
    InvertedFunctionTableLock: _EX_PUSH_LOCK,
    ActiveThreadsHighWatermark: Uint4B,
    LargePrivateVadCount: Uint4B,
    ThreadListLock: _EX_PUSH_LOCK,
    WnfContext: *mut Void,
    ServerSilo: *mut _EJOB,
    SignatureLevel: UChar,
    SectionSignatureLevel: UChar,
    Protection: _PS_PROTECTION,
    /*HangCount        : Pos 0, 3 Bits,
    GhostCount       : Pos 3, 3 Bits,
    PrefilterException : Pos 6, 1 Bit,
    Flags3           : Uint4B,
    Minimal          : Pos 0, 1 Bit,
    ReplacingPageRoot : Pos 1, 1 Bit,
    Crashed          : Pos 2, 1 Bit,
    JobVadsAreTracked : Pos 3, 1 Bit,
    VadTrackingDisabled : Pos 4, 1 Bit,
    AuxiliaryProcess : Pos 5, 1 Bit,
    SubsystemProcess : Pos 6, 1 Bit,
    IndirectCpuSets  : Pos 7, 1 Bit,
    RelinquishedCommit : Pos 8, 1 Bit,
    HighGraphicsPriority : Pos 9, 1 Bit,
    CommitFailLogged : Pos 10, 1 Bit,
    ReserveFailLogged : Pos 11, 1 Bit,
    SystemProcess    : Pos 12, 1 Bit,
    AllImagesAtBasePristineBase : Pos 13, 1 Bit,
    AddressPolicyFrozen : Pos 14, 1 Bit,
    ProcessFirstResume : Pos 15, 1 Bit,
    ForegroundExternal : Pos 16, 1 Bit,
    ForegroundSystem : Pos 17, 1 Bit,
    HighMemoryPriority : Pos 18, 1 Bit,
    EnableProcessSuspendResumeLogging : Pos 19, 1 Bit,
    EnableThreadSuspendResumeLogging : Pos 20, 1 Bit,
    SecurityDomainChanged : Pos 21, 1 Bit,
    SecurityFreezeComplete : Pos 22, 1 Bit,
    VmProcessorHost  : Pos 23, 1 Bit,
    VmProcessorHostTransition : Pos 24, 1 Bit,
    AltSyscall       : Pos 25, 1 Bit,
    TimerResolutionIgnore : Pos 26, 1 Bit,
    DisallowUserTerminate : Pos 27, 1 Bit,
    EnableProcessRemoteExecProtectVmLogging : Pos 28, 1 Bit,
    EnableProcessLocalExecProtectVmLogging : Pos 29, 1 Bit,
    MemoryCompressionProcess : Pos 30, 1 Bit,
    EnableProcessImpersonationLogging : Pos 31, 1 Bit*/
    DeviceAsid: Int4B,
    SvmData: *mut Void,
    SvmProcessLock: _EX_PUSH_LOCK,
    SvmLock: Uint8B,
    SvmProcessDeviceListHead: _LIST_ENTRY,
    LastFreezeInterruptTime: Uint8B,
    DiskCounters: *mut _PROCESS_DISK_COUNTERS,
    PicoContext: *mut Void,
    EnclaveTable: *mut Void,
    EnclaveNumber: Uint8B,
    EnclaveLock: _EX_PUSH_LOCK,
    HighPriorityFaultsAllowed: Uint4B,
    EnergyContext: *mut _PO_PROCESS_ENERGY_CONTEXT,
    VmContext: *mut Void,
    SequenceNumber: Uint8B,
    CreateInterruptTime: Uint8B,
    CreateUnbiasedInterruptTime: Uint8B,
    TotalUnbiasedFrozenTime: Uint8B,
    LastAppStateUpdateTime: Uint8B,
    /*LastAppStateUptime : Pos 0, 61 Bits,
    LastAppState     : Pos 61, 3 Bits*/
    SharedCommitCharge: Uint8B,
    SharedCommitLock: _EX_PUSH_LOCK,
    SharedCommitLinks: _LIST_ENTRY,
    AllowedCpuSets: Uint8B,
    DefaultCpuSets: Uint8B,
    AllowedCpuSetsIndirect: *mut Uint8B,
    DefaultCpuSetsIndirect: *mut Uint8B,
    DiskIoAttribution: *mut Void,
    DxgProcess: *mut Void,
    Win32KFilterSet: Uint4B,
    Machine: Uint2B,
    MmSlabIdentity: UChar,
    Spare0: UChar,
    ProcessTimerDelay: _PS_INTERLOCKED_TIMER_DELAY_VALUES,
    KTimerSets: Uint4B,
    KTimer2Sets: Uint4B,
    ThreadTimerSets: Uint4B,
    VirtualTimerListLock: Uint8B,
    VirtualTimerListHead: _LIST_ENTRY,
    WakeChannel: _WNF_STATE_NAME,
    WakeInfo: _PS_PROCESS_WAKE_INFORMATION,
    MitigationFlags: Uint4B,
    MitigationFlagsValues: Uint4B,
    MitigationFlags2: Uint4B,
    MitigationFlags2Values: Uint4B,
    PartitionObject: *mut Void,
    SecurityDomain: Uint8B,
    ParentSecurityDomain: Uint8B,
    CoverageSamplerContext: *mut Void,
    MmHotPatchContext: *mut Void,
    DynamicEHContinuationTargetsTree: _RTL_AVL_TREE,
    DynamicEHContinuationTargetsLock: _EX_PUSH_LOCK,
    DynamicEnforcedCetCompatibleRanges: _PS_DYNAMIC_ENFORCED_ADDRESS_RANGES,
    DisabledComponentFlags: Uint4B,
    PageCombineSequence: Int4B,
    EnableOptionalXStateFeaturesLock: _EX_PUSH_LOCK,
    PathRedirectionHashes: *mut Uint4B,
    SyscallProvider: *mut _PS_SYSCALL_PROVIDER,
    SyscallProviderProcessLinks: _LIST_ENTRY,
    SyscallProviderDispatchContext: _PSP_SYSCALL_PROVIDER_DISPATCH_CONTEXT,
    MitigationFlags3: Uint4B,
    MitigationFlags3Values: Uint4B,
    Flags4: Uint4B,
    /*ThreadWasActive  : Pos 0, 1 Bit,
    MinimalTerminate : Pos 1, 1 Bit,
    ImageExpansionDisable : Pos 2, 1 Bit,
    SessionFirstProcess : Pos 3, 1 Bit*/
    SyscallUsage: Uint4B,
    SyscallUsageValues: Uint4B,
    SupervisorDeviceAsid: Int4B,
    SupervisorSvmData: *mut Void,
    NetworkCounters: *mut _PROCESS_NETWORK_COUNTERS,
    Execution: _PROCESS_EXECUTION,
    ThreadIndexTable: *mut Void,
    FreezeWorkLinks: _LIST_ENTRY,
    PpmPolicyLock: _EX_PUSH_LOCK,
    BamPpmPolicy: Uint4B,
}
