use kernel_type::KernelType;
use wdk_sys::*;

pub mod eprocess;
pub mod peb;
pub mod unicode_string;

use eprocess::*;

pub type Void = core::ffi::c_void;
pub type UChar = u8;
pub type Uint2B = u16;
pub type Uint4B = u32;
pub type Uint8B = u64;
pub type Char = i8;
pub type Int4B = i32;
pub type Int8B = i64;
pub type _KAB_UM_PROCESS_CONTEXT = [Void; 2];
pub type _KEXECUTE_OPTIONS = [UChar; 5];
pub type _KGROUP_MASK = [Void; 2];
pub type _KI_IDEAL_PROCESSOR_ASSIGNMENT_BLOCK = Void;
pub type _KSTACK_COUNT = Void;
pub type _KSCHEDULING_GROUP = Void;
pub type _KPROCESS_AVAILABLE_CPU_STATE = Void;
pub type _KPROCESS = KPROCESS;
pub type _EX_PUSH_LOCK = Void;
pub type _EX_FAST_REF = Void;
pub type _ETHREAD = Void;
pub type _RTL_AVL_TREE = Void;
pub type _PAGEFAULT_HISTORY = Void;
pub type _PSP_SESSION_SPACE = Void;
pub type _EPROCESS_QUOTA_BLOCK = Void;
pub type _HANDLE_TABLE = Void;
pub type _EWOW64PROCESS = Void;
pub type _SE_AUDIT_PROCESS_CREATION_INFO = Void;
pub type _MMSUPPORT_FULL = [u8; 0x140];
pub type _ALPC_PROCESS_CONTEXT = [u8; 0x20];
pub type _PO_DIAG_STACK_RECORD = Void;
pub type _INVERTED_FUNCTION_TABLE_KERNEL_MODE = Void;
pub type _PS_PROTECTION = u8;
pub type _PROCESS_DISK_COUNTERS = Void;
pub type _PO_PROCESS_ENERGY_CONTEXT = Void;
pub type _PS_INTERLOCKED_TIMER_DELAY_VALUES = Void;
pub type _PS_PROCESS_WAKE_INFORMATION = [u8; 0x30];
pub type _PS_DYNAMIC_ENFORCED_ADDRESS_RANGES = [Void; 2];
pub type _PS_SYSCALL_PROVIDER = Void;
pub type _PSP_SYSCALL_PROVIDER_DISPATCH_CONTEXT = Void;
pub type _PROCESS_EXECUTION = Void;
pub type _EPROCESS = EPROCESS;
