use super::*;

extern crate alloc;

use super::unicode_string::UnicodeString;

#[repr(C, align(8))]
#[derive(KernelType)]
pub struct PEB {
    pub inherited_address_space: UChar,
    pub read_image_file_exec_options: UChar,
    pub being_debugged: UChar,
    pub bit_field: UChar,
    pub mutant: *mut Void,
    pub image_base_address: *mut Void,
    pub ldr: *mut Void, //_PEB_LDR_DATA,
    pub process_parameters: RtlUserProcessParameters,
    pub sub_system_data: *mut Void,
    pub process_heap: *mut Void,
    pub fast_peb_lock: *mut Void, // _RTL_CRITICAL_SECTION,
    pub atl_thunk_slist_ptr: *mut _SLIST_HEADER,
    pub ifeo_key: *mut Void,
    pub cross_process_flags: Uint4B,
    pub kernel_callback_table: *mut Void,
    pub user_shared_info_ptr: *mut Void,
    pub system_reserved: Uint4B,
    pub atl_thunk_slist_ptr32: Uint4B,
    pub api_set_map: *mut Void,
    pub tls_expansion_counter: Uint4B,
    pub tls_bitmap: *mut Void,
    pub tls_bitmap_bits: [Uint4B; 2],
    pub read_only_shared_memory_base: *mut Void,
    pub shared_data: *mut Void,
    pub read_only_static_server_data: *mut *mut Void,
    pub ansi_code_page_data: *mut Void,
    pub oem_code_page_data: *mut Void,
    pub unicode_case_table_data: *mut Void,
    pub number_of_processors: Uint4B,
    pub nt_global_flag: Uint4B,
    pub critical_section_timeout: _LARGE_INTEGER,
    pub heap_segment_reserve: Uint8B,
    pub heap_segment_commit: Uint8B,
    pub heap_de_commit_total_free_threshold: Uint8B,
    pub heap_de_commit_free_block_threshold: Uint8B,
    pub number_of_heaps: Uint4B,
    pub maximum_number_of_heaps: Uint4B,
    pub process_heaps: *mut *mut Void,
    pub gdi_shared_handle_table: *mut Void,
    pub process_starter_helper: *mut Void,
    pub gdi_dc_attribute_list: Uint4B,
    pub loader_lock: *mut Void,
    pub os_major_version: Uint4B,
    pub os_minor_version: Uint4B,
    pub os_build_number: Uint2B,
    pub os_csd_version: Uint2B,
    pub os_platform_id: Uint4B,
    pub image_subsystem: Uint4B,
    pub image_subsystem_major_version: Uint4B,
    pub image_subsystem_minor_version: Uint4B,
    pub active_process_affinity_mask: Uint8B,
    pub gdi_handle_buffer: [Uint4B; 60],
    pub post_process_init_routine: *mut Void,
    pub tls_expansion_bitmap: *mut Void, // _RTL_BITMAP,
    pub tls_expansion_bitmap_bits: [Uint4B; 32],
    pub session_id: Uint4B,
    pub app_compat_flags: _ULARGE_INTEGER,
    pub app_compat_flags_user: _ULARGE_INTEGER,
    pub p_shim_data: *mut Void,
    pub app_compat_info: *mut Void,
    pub csd_version: _UNICODE_STRING,
    pub activation_context_data: *mut Void, //_ACTIVATION_CONTEXT_DATA,
    pub process_assembly_storage_map: *mut Void, //_ASSEMBLY_STORAGE_MAP,
    pub system_default_activation_context_data: *mut Void, // _ACTIVATION_CONTEXT_DATA,
    pub system_assembly_storage_map: *mut Void, //_ASSEMBLY_STORAGE_MAP
    pub minimum_stack_commit: Uint8B,
    pub spare_pointers: [*mut Void; 2],
    pub patch_loader_data: *mut Void,
    pub chpe_v2_process_info: *mut Void,
    pub app_model_feature_state: Uint4B,
    pub spare_ulongs: [Uint4B; 2],
    pub active_code_page: Uint2B,
    pub oem_code_page: Uint2B,
    pub use_case_mapping: Uint2B,
    pub unused_nls_field: Uint2B,
    pub wer_registration_data: *mut Void,
    pub wer_ship_assert_ptr: *mut Void,
    pub ec_code_bit_map: *mut Void,
    pub p_image_header_hash: *mut Void,
    pub tracing_flags: Uint4B,
    pub csr_server_read_only_shared_memory_base: Uint8B,
    pub tpp_workerp_list_lock: Uint8B,
    pub tpp_workerp_list: _LIST_ENTRY,
    pub wait_on_address_hash_table: [*mut Void; 128],
    pub telemetry_coverage_header: *mut Void,
    pub cloud_file_flags: Uint4B,
    pub cloud_file_diag_flags: Uint4B,
    pub placeholder_compatibility_mode: Char,
    pub leap_second_data: *mut Void,
    pub leap_second_flags: Uint4B,
    pub nt_global_flag2: Uint4B,
    pub extended_feature_disable_mask: Uint8B,
    pub win32_client_proc_info: *mut Void,
}

#[repr(C, align(8))]
#[derive(KernelType)]
pub struct RTL_USER_PROCESS_PARAMETERS {
    pub maximum_length: u32,
    pub length: u32,
    pub flags: u32,
    pub debug_flags: u32,
    pub console_handle: PVOID,
    pub console_flags: u32,
    pub standard_input: PVOID,
    pub standard_output: PVOID,
    pub standard_error: PVOID,
    pub current_directory: CURDIR,
    pub dll_path: UnicodeString,
    pub image_path_name: UnicodeString,
    pub command_line: UnicodeString,
    pub environment: PVOID,
    pub starting_x: u32,
    pub starting_y: u32,
    pub count_x: u32,
    pub count_y: u32,
    pub count_chars_x: u32,
    pub count_chars_y: u32,
    pub fill_attribute: u32,
    pub window_flags: u32,
    pub show_window_flags: u32,
    pub window_title: UnicodeString,
    pub desktop_info: UnicodeString,
    pub shell_info: UnicodeString,
    pub runtime_data: UnicodeString,
    pub current_directores: [RTL_DRIVE_LETTER_CURDIR; 32],
    pub environment_size: u64,
    pub environment_version: u64,
    pub package_dependency_data: PVOID,
    pub process_group_id: u32,
    pub loader_threads: u32,
    pub redirection_dll_name: UnicodeString,
    pub heap_partition_name: UnicodeString,
    pub default_threadpool_cpu_set_masks: *mut u64,
    pub default_threadpool_cpu_set_mask_count: u32,
    pub default_threadpool_thread_maximum: u32,
    pub heap_memory_type_mask: u32,
    pub attribute_list: PVOID,
}

#[repr(C, align(8))]
pub struct RTL_DRIVE_LETTER_CURDIR {
    pub flags: u16,
    pub length: u16,
    pub time_stamp: u32,
    pub dos_path: UNICODE_STRING,
}

#[repr(C, align(8))]
pub struct CURDIR {
    pub dos_path: UNICODE_STRING,
    pub handle: HANDLE,
}
