[package]
name = "windows_types"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
        "./windows_type",
]

[package.metadata.wdk.driver-model]
driver-type = "WDM"

[features]
kernel = ["dep:wdk-sys"]
user = ["dep:windows_type"]

[build-dependencies]
wdk-build = "0.5.1"

[dependencies]
wdk-sys = { version = "0.5.1", optional = true}
windows_type = { path = "./windows_type/", optional = true }
